### ISSUE TITLE
Is the bot controller supposed to do anything?

### ISSUE THREAD

**Issue by FreezePhoenix** [NexusNull/ALBot#1]
When I run the code, and navigate to my controller, it shows up as a black screen. I get a few errors in the console when I run however: 
```
{ Error: listen EACCES 0.0.0.0:81
    at Server.setupListenHandle [as _listen2] (net.js:1329:19)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at Function.listen (/home/runner/node_modules/express/lib/application.js:618:24)
    at WebServer.openSocket (/home/runner/node_modules/bot-web-interface/webServer/WebServer.js:24:9)
    at Object.startOnPort (/home/runner/node_modules/bot-web-interface/main.js:11:19)
    at main (/home/runner/index.js:77:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 81 }
Error: listen EACCES 0.0.0.0:81
    at Server.setupListenHandle [as _listen2] (net.js:1329:19)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at Function.listen (/home/runner/node_modules/express/lib/application.js:618:24)
    at WebServer.openSocket (/home/runner/node_modules/bot-web-interface/webServer/WebServer.js:24:9)
    at Object.startOnPort (/home/runner/node_modules/bot-web-interface/main.js:11:19)
    at main (/home/runner/index.js:77:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
{ Error: listen EACCES 0.0.0.0:82
    at Server.setupListenHandle [as _listen2] (net.js:1329:19)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at Server.listen.Server.attach (/home/runner/node_modules/socket.io/lib/index.js:273:9)
    at new Server (/home/runner/node_modules/socket.io/lib/index.js:59:17)
    at SocketServer.openSocket (/home/runner/node_modules/bot-web-interface/webServer/SocketServer.js:39:15)
    at Object.startOnPort (/home/runner/node_modules/bot-web-interface/main.js:12:22)
    at main (/home/runner/index.js:77:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 82 }
Error: listen EACCES 0.0.0.0:82
    at Server.setupListenHandle [as _listen2] (net.js:1329:19)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at Server.listen.Server.attach (/home/runner/node_modules/socket.io/lib/index.js:273:9)
    at new Server (/home/runner/node_modules/socket.io/lib/index.js:59:17)
    at SocketServer.openSocket (/home/runner/node_modules/bot-web-interface/webServer/SocketServer.js:39:15)
    at Object.startOnPort (/home/runner/node_modules/bot-web-interface/main.js:12:22)
    at main (/home/runner/index.js:77:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by NexusNull** [comment]
Well it seems you don't have permission to bind to the port 81 and 82.
Go into the userdata.conf and change the base port to something > 1000. You could also start node with root but that's really not a good idea.
If you don't want the BWI to run you can also just disable it.

**Comment by FreezePhoenix** [comment]
I changed the number, and I get errors like this: 
```GET <url>:81/socket.io/?EIO=3&transport=polling&t=MSIHdy2 net::ERR_CONNECTION_TIMED_OUT```
Is this something to do with the default config?

**Comment by NexusNull** [comment]
Mmh, what have you done to fix the issue? It seems you haven't changed the port so I assume you gave it permission to run on that port. It might be because you have a firewall rule in place to block the access.

**Comment by FreezePhoenix** [comment]
@NexusNull I did change the port in my config, but the socket.js file seems to assume that it's still on port 81.

**Comment by NexusNull** [comment]
There is no socket.js file. I started the bot on my end and changed the port numbers to 1081 and everything works. 
I made a [screenshot](https://pwellershaus.com/uploads/original/0a2ebf340cc3d933a3a9e74db48634dd.png) so you can take a look at my setup.

**Comment by FreezePhoenix** [comment]
Ah. You're running it on localhost. That may be the issue.

*Meanwhile, I'm reinventing the socket using `send_cm`*

**Comment by FreezePhoenix** [comment]
@NexusNull I think I know the issue occurred. It's set up to run on client, not on a webserver. If you could release a version of bot-web-interface for webservers, that would be nice :) I think that should't be difficult, you just need to clone this repo and change it to have the actual socket.io file, not the client variety.

**Comment by NexusNull** [comment]
The issue has nothing to do with the actual socket.io file, the project needs socket.io to comunicate between server and client. The problem is that repl.it remaps ports this causes things to break. There is a possibility that I can get it to work by combining socket.io into the "webserver". Webserver is in quotes because it isn't a real webserver either it's still node running express.

**Comment by FreezePhoenix** [comment]
@NexusNull I got it to work: 
![image](https://user-images.githubusercontent.com/24441367/48626955-46a3e800-e981-11e8-8440-1d21c53a3ff4.png) But I notice one thing missing: Where is the gold counter?
