### ISSUE TITLE
Error in raspberry pi 3b+ when running main

### ISSUE THREAD

**Issue by ftpavan** [NexusNull/ALBot#30]
Hey, I just tried to run the node main in my raspberry pi 3b+ but im getting an error related to the userData file. I did the rename part and everything...

pi@raspberrypi:~/ALBot $ node main
/home/pi/ALBot/userData:2
    "config": {
            ^
SyntaxError: Unexpected token :
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/ALBot/app/httpWrapper.js:4:16)
/home/pi/ALBot/userData:2
    "config": {
            ^
SyntaxError: Unexpected token :
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/ALBot/app/httpWrapper.js:4:16)

**Comment by NexusNull** [comment]
Could you upload your userdata.json?
Without credentials of course.

**Comment by ftpavan** [comment]
Here https://we.tl/t-g2LI9NcH0W

**Comment by ftpavan** [comment]
Well I made the copying step again and Im getting a different error:

{ Error: Cannot find module '../userData'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/ALBot/app/httpWrapper.js:4:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
Error: Cannot find module '../userData'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/ALBot/app/httpWrapper.js:4:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by NexusNull** [comment]
The issue is probably that the documentation says to rename it to userdata.json but the script expects userData.json.
It should probably work if you rename the file to userData.json.
I'll update the readme in the mean time

**Comment by ftpavan** [comment]
Yes, the renaming fixed it, thanks.

Im getting the following error now, with my characters already enabled in userData.json.

check Login:
logged in
Reading game data from cache
Reading game data from cache
node: ../deps/uv/src/unix/core.c:166: uv_close: Assertion `0' failed.
node: ../deps/uv/src/unix/core.c:166: uv_close: Assertion `0' failed.


and nothing else happens

**Comment by NexusNull** [comment]
Sadly I can reproduce this issue, could you get in touch with my over discord so I can try investigating it on your machine?

**Comment by ftpavan** [comment]
Sure, whats your nickname#ID?

**Comment by NexusNull** [comment]
It looks like the issue was just an issue with the node version 7.9.0 updating to a newer version seems to fix the issue, in this case we updated to 8.10.0
